-- 3FJ Droguerie - Supabase schema
-- Run this SQL in Supabase SQL Editor.

create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.products (
  id text primary key,
  slug text not null unique,
  name text not null,
  price integer not null check (price > 0),
  stock integer not null default 0 check (stock >= 0),
  bulk_price_tiers jsonb not null default '[]'::jsonb,
  short_description text not null,
  description text not null,
  category_slug text not null,
  rating numeric(2, 1) not null default 4.5 check (rating >= 0 and rating <= 5),
  images text[] not null check (cardinality(images) > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
add column if not exists stock integer not null default 0 check (stock >= 0);

alter table public.products
add column if not exists bulk_price_tiers jsonb not null default '[]'::jsonb;

alter table public.products
drop constraint if exists products_bulk_price_tiers_is_array_check;

alter table public.products
add constraint products_bulk_price_tiers_is_array_check
check (jsonb_typeof(bulk_price_tiers) = 'array');

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

create index if not exists idx_products_category_slug on public.products(category_slug);
create index if not exists idx_products_slug on public.products(slug);
create index if not exists idx_products_active on public.products(is_active);

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id text not null references public.products(id) on delete cascade,
  color text null,
  size text null,
  price integer not null check (price > 0),
  previous_price integer null check (previous_price > price),
  stock integer not null default 0 check (stock >= 0),
  sku text null,
  image text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_variants_color_or_size_check check (color is not null or size is not null)
);

drop trigger if exists trg_product_variants_updated_at on public.product_variants;
create trigger trg_product_variants_updated_at
before update on public.product_variants
for each row
execute function public.set_updated_at();

create index if not exists idx_product_variants_product_id on public.product_variants(product_id);
create index if not exists idx_product_variants_active on public.product_variants(is_active);
create index if not exists idx_product_variants_color on public.product_variants(color);
create index if not exists idx_product_variants_size on public.product_variants(size);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid null references auth.users(id) on delete set null,
  fulfillment_method text not null default 'delivery' check (fulfillment_method in ('delivery', 'pickup')),
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  customer_location text not null default 'Fes',
  subtotal integer not null check (subtotal >= 0),
  delivery_fee integer not null check (delivery_fee >= 0),
  total integer not null check (total >= 0),
  status text not null default 'new' check (status in ('new', 'confirmed', 'preparing', 'ready', 'shipped', 'collected', 'delivered', 'cancelled')),
  admin_note text null,
  constraint orders_status_fulfillment_compat_check check (
    (
      fulfillment_method = 'delivery'
      and status in ('new', 'confirmed', 'shipped', 'delivered', 'cancelled')
    )
    or (
      fulfillment_method = 'pickup'
      and status in ('new', 'confirmed', 'preparing', 'ready', 'collected', 'cancelled')
    )
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_user_id on public.orders(user_id);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null references public.products(id),
  variant_id uuid null,
  selected_color text null,
  selected_size text null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0),
  line_total integer not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

alter table public.order_items
add column if not exists variant_id uuid;

alter table public.order_items
add column if not exists selected_color text;

alter table public.order_items
add column if not exists selected_size text;

create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_order_items_product_id on public.order_items(product_id);

create table if not exists public.quote_requests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id uuid null references auth.users(id) on delete set null,
  anonymous_id text not null,
  payload jsonb not null,
  status text not null default 'new',
  constraint quote_requests_status_check check (status in ('new', 'contacted', 'converted', 'closed')),
  constraint quote_requests_payload_object_check check (jsonb_typeof(payload) = 'object'),
  constraint quote_requests_anonymous_id_length_check check (char_length(btrim(anonymous_id)) >= 6)
);

drop trigger if exists trg_quote_requests_updated_at on public.quote_requests;
create trigger trg_quote_requests_updated_at
before update on public.quote_requests
for each row
execute function public.set_updated_at();

create index if not exists idx_quote_requests_created_at on public.quote_requests(created_at desc);
create index if not exists idx_quote_requests_status on public.quote_requests(status);
create index if not exists idx_quote_requests_user_id on public.quote_requests(user_id);
create index if not exists idx_quote_requests_anonymous_id on public.quote_requests(anonymous_id);

create or replace function public.create_order_with_items_atomic(
  p_customer_name text,
  p_customer_phone text,
  p_customer_address text,
  p_customer_location text,
  p_subtotal integer,
  p_delivery_fee integer,
  p_total integer,
  p_user_id uuid,
  p_items jsonb,
  p_fulfillment_method text default 'delivery'
)
returns uuid
language plpgsql
as $$
declare
  v_order_id uuid;
  v_item record;
  v_rows integer;
  v_fulfillment_method text;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'ORDER_ITEMS_EMPTY';
  end if;

  if p_subtotal < 0 or p_delivery_fee < 0 or p_total < 0 or p_total <> (p_subtotal + p_delivery_fee) then
    raise exception 'INVALID_ORDER_TOTALS';
  end if;

  if p_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  v_fulfillment_method := coalesce(nullif(btrim(p_fulfillment_method), ''), 'delivery');
  if v_fulfillment_method not in ('delivery', 'pickup') then
    raise exception 'INVALID_FULFILLMENT_METHOD';
  end if;

  for v_item in
    select *
    from jsonb_to_recordset(p_items) as item(
      product_id text,
      variant_id text,
      selected_color text,
      selected_size text,
      product_name text,
      quantity integer,
      unit_price integer,
      line_total integer
    )
  loop
    if v_item.product_id is null or btrim(v_item.product_id) = '' then
      raise exception 'INVALID_PRODUCT_ID';
    end if;

    if v_item.product_name is null or btrim(v_item.product_name) = '' then
      raise exception 'INVALID_PRODUCT_NAME';
    end if;

    if v_item.quantity is null or v_item.quantity <= 0 then
      raise exception 'INVALID_ITEM_QUANTITY';
    end if;

    if v_item.unit_price is null or v_item.unit_price < 0 then
      raise exception 'INVALID_UNIT_PRICE';
    end if;

    if v_item.line_total is null or v_item.line_total <> (v_item.quantity * v_item.unit_price) then
      raise exception 'INVALID_LINE_TOTAL';
    end if;

    if v_item.variant_id is null or btrim(v_item.variant_id) = '' then
      update public.products
      set stock = stock - v_item.quantity
      where id = v_item.product_id
        and stock >= v_item.quantity;

      get diagnostics v_rows = row_count;
      if v_rows <> 1 then
        raise exception 'INSUFFICIENT_STOCK';
      end if;
    else
      update public.product_variants
      set stock = stock - v_item.quantity
      where id = v_item.variant_id::uuid
        and product_id = v_item.product_id
        and is_active = true
        and stock >= v_item.quantity;

      get diagnostics v_rows = row_count;
      if v_rows <> 1 then
        raise exception 'INSUFFICIENT_VARIANT_STOCK';
      end if;
    end if;
  end loop;

  insert into public.orders (
    user_id,
    fulfillment_method,
    customer_name,
    customer_phone,
    customer_address,
    customer_location,
    subtotal,
    delivery_fee,
    total
  )
  values (
    p_user_id,
    v_fulfillment_method,
    p_customer_name,
    p_customer_phone,
    p_customer_address,
    p_customer_location,
    p_subtotal,
    p_delivery_fee,
    p_total
  )
  returning id into v_order_id;

  insert into public.order_items (
    order_id,
    product_id,
    variant_id,
    selected_color,
    selected_size,
    product_name,
    quantity,
    unit_price,
    line_total
  )
  select
    v_order_id,
    item.product_id,
    item.variant_id::uuid,
    item.selected_color,
    item.selected_size,
    item.product_name,
    item.quantity,
    item.unit_price,
    item.line_total
  from jsonb_to_recordset(p_items) as item(
    product_id text,
    variant_id text,
    selected_color text,
    selected_size text,
    product_name text,
    quantity integer,
    unit_price integer,
    line_total integer
  );

  return v_order_id;
end;
$$;

create table if not exists public.offers (
  id text primary key,
  title text not null,
  short_description text not null,
  discount_label text not null,
  product_id text not null references public.products(id),
  discount_type text not null,
  discount_value numeric(10, 2) not null,
  discounted_price integer null check (discounted_price > 0),
  start_at timestamptz null,
  end_at timestamptz null,
  image_path text null,
  banner_text text null,
  is_active boolean not null default true,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint offers_date_range_check check (end_at is null or start_at is null or end_at > start_at),
  constraint offers_discount_type_check check (discount_type in ('percent', 'fixed')),
  constraint offers_discount_value_check check (discount_value >= 0),
  constraint offers_discount_percent_range_check check (discount_type <> 'percent' or discount_value <= 100)
);

alter table public.offers
add column if not exists product_id text references public.products(id);

alter table public.offers
add column if not exists discount_type text;

alter table public.offers
add column if not exists discount_value numeric(10, 2);

alter table public.offers
add column if not exists discounted_price integer check (discounted_price > 0);

update public.offers as current_offer
set
  discount_type = 'fixed',
  discount_value = greatest(
    0,
    linked_product.price - coalesce(current_offer.discounted_price, linked_product.price)
  )
from public.products as linked_product
where current_offer.product_id = linked_product.id
  and (current_offer.discount_type is null or current_offer.discount_value is null);

update public.offers
set discount_type = 'fixed'
where discount_type is null;

update public.offers
set discount_value = 0
where discount_value is null;

alter table public.offers
alter column discounted_price drop not null;

alter table public.offers
drop constraint if exists offers_discount_type_check;

alter table public.offers
drop constraint if exists offers_discount_value_check;

alter table public.offers
drop constraint if exists offers_discount_percent_range_check;

alter table public.offers
add constraint offers_discount_type_check
check (discount_type in ('percent', 'fixed'));

alter table public.offers
add constraint offers_discount_value_check
check (discount_value >= 0);

alter table public.offers
add constraint offers_discount_percent_range_check
check (discount_type <> 'percent' or discount_value <= 100);

alter table public.offers
alter column discount_type set not null;

alter table public.offers
alter column discount_value set not null;

drop trigger if exists trg_offers_updated_at on public.offers;
create trigger trg_offers_updated_at
before update on public.offers
for each row
execute function public.set_updated_at();

create index if not exists idx_offers_active on public.offers(is_active);
create index if not exists idx_offers_featured on public.offers(is_featured);
create index if not exists idx_offers_end_at on public.offers(end_at);
create index if not exists idx_offers_product_id on public.offers(product_id);
create index if not exists idx_offers_discount_type on public.offers(discount_type);

create table if not exists public.ads (
  id uuid primary key default gen_random_uuid(),
  image_url text not null,
  title text null,
  description text null,
  link text not null,
  position text not null,
  is_active boolean not null default false,
  start_date timestamptz null,
  end_date timestamptz null,
  created_at timestamptz not null default now(),
  constraint ads_position_check check (position in ('top', 'middle')),
  constraint ads_date_range_check check (end_date is null or start_date is null or end_date > start_date)
);

create index if not exists idx_ads_is_active on public.ads(is_active);
create index if not exists idx_ads_position on public.ads(position);
create index if not exists idx_ads_created_at on public.ads(created_at desc);
create index if not exists idx_ads_start_date on public.ads(start_date);
create index if not exists idx_ads_end_date on public.ads(end_date);

create table if not exists public.ad_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text null,
  position text not null,
  duration_days integer not null,
  price integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint ad_plans_position_check check (position in ('top', 'middle')),
  constraint ad_plans_duration_days_check check (duration_days > 0),
  constraint ad_plans_price_check check (price >= 0)
);

create index if not exists idx_ad_plans_position on public.ad_plans(position);
create index if not exists idx_ad_plans_is_active on public.ad_plans(is_active);
create index if not exists idx_ad_plans_created_at on public.ad_plans(created_at desc);

alter table public.ads
add column if not exists plan_id uuid references public.ad_plans(id) on delete set null;

create index if not exists idx_ads_plan_id on public.ads(plan_id);

create table if not exists public.ad_events (
  id bigint generated by default as identity primary key,
  ad_id uuid not null references public.ads(id) on delete cascade,
  event_type text not null,
  session_key text null,
  dedupe_key text null,
  created_at timestamptz not null default now(),
  constraint ad_events_event_type_check check (event_type in ('view', 'click'))
);

create index if not exists idx_ad_events_ad_id on public.ad_events(ad_id);
create index if not exists idx_ad_events_event_type on public.ad_events(event_type);
create index if not exists idx_ad_events_created_at on public.ad_events(created_at desc);
create unique index if not exists idx_ad_events_dedupe_key_unique
on public.ad_events(dedupe_key)
where dedupe_key is not null;

create table if not exists public.blog_posts (
  id text primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null,
  content text not null,
  cover_image_path text not null,
  seo_title text null,
  seo_description text null,
  is_published boolean not null default false,
  published_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_blog_posts_updated_at on public.blog_posts;
create trigger trg_blog_posts_updated_at
before update on public.blog_posts
for each row
execute function public.set_updated_at();

create index if not exists idx_blog_posts_slug on public.blog_posts(slug);
create index if not exists idx_blog_posts_is_published on public.blog_posts(is_published);
create index if not exists idx_blog_posts_published_at on public.blog_posts(published_at desc);

create table if not exists public.reviews (
  id text primary key,
  customer_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  testimonial_text text not null,
  role text null,
  avatar_image_path text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_reviews_updated_at on public.reviews;
create trigger trg_reviews_updated_at
before update on public.reviews
for each row
execute function public.set_updated_at();

create index if not exists idx_reviews_is_active on public.reviews(is_active);
create index if not exists idx_reviews_created_at on public.reviews(created_at desc);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create index if not exists idx_favorites_user_id_created_at on public.favorites(user_id, created_at desc);

alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.offers enable row level security;
alter table public.ads enable row level security;
alter table public.ad_plans enable row level security;
alter table public.ad_events enable row level security;
alter table public.blog_posts enable row level security;
alter table public.reviews enable row level security;
alter table public.favorites enable row level security;
alter table public.quote_requests enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Public can read active product variants" on public.product_variants;
create policy "Public can read active product variants"
on public.product_variants
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Public can read active offers" on public.offers;
create policy "Public can read active offers"
on public.offers
for select
to anon, authenticated
using (
  is_active = true
  and (start_at is null or start_at <= now())
  and (end_at is null or end_at > now())
);

drop policy if exists "Public can read active scheduled ads" on public.ads;
create policy "Public can read active scheduled ads"
on public.ads
for select
to anon, authenticated
using (
  is_active = true
  and (start_date is null or start_date <= now())
  and (end_date is null or end_date > now())
);

drop policy if exists "Public can read published blog posts" on public.blog_posts;
create policy "Public can read published blog posts"
on public.blog_posts
for select
to anon, authenticated
using (
  is_published = true
  and (published_at is null or published_at <= now())
);

drop policy if exists "Public can read active reviews" on public.reviews;
create policy "Public can read active reviews"
on public.reviews
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Authenticated users can read own orders" on public.orders;
create policy "Authenticated users can read own orders"
on public.orders
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Authenticated users can cancel own recent new orders" on public.orders;
create policy "Authenticated users can cancel own recent new orders"
on public.orders
for update
to authenticated
using (
  auth.uid() = user_id
  and status = 'new'
  and created_at >= now() - interval '2 hour'
)
with check (
  auth.uid() = user_id
  and status = 'cancelled'
);

drop policy if exists "Authenticated users can read own quote requests" on public.quote_requests;
create policy "Authenticated users can read own quote requests"
on public.quote_requests
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Authenticated users can create own quote requests" on public.quote_requests;
create policy "Authenticated users can create own quote requests"
on public.quote_requests
for insert
to authenticated
with check (user_id is null or auth.uid() = user_id);

drop policy if exists "Anonymous users can create quote requests" on public.quote_requests;
create policy "Anonymous users can create quote requests"
on public.quote_requests
for insert
to anon
with check (user_id is null);

drop policy if exists "Service role can read quote requests" on public.quote_requests;
create policy "Service role can read quote requests"
on public.quote_requests
for select
to service_role
using (true);

drop policy if exists "Service role can update quote requests" on public.quote_requests;
create policy "Service role can update quote requests"
on public.quote_requests
for update
to service_role
using (true)
with check (true);

drop policy if exists "Authenticated users can read own favorites" on public.favorites;
create policy "Authenticated users can read own favorites"
on public.favorites
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Authenticated users can add own favorites" on public.favorites;
create policy "Authenticated users can add own favorites"
on public.favorites
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Authenticated users can remove own favorites" on public.favorites;
create policy "Authenticated users can remove own favorites"
on public.favorites
for delete
to authenticated
using (auth.uid() = user_id);
