-- 3FJ Droguerie - products seed (30 products with photos)
-- Run after schema.sql.

insert into public.products (
  id,
  slug,
  name,
  price,
  stock,
  short_description,
  description,
  category_slug,
  rating,
  images,
  is_active
)
values
(
  'peinture-atlas-20kg',
  'peinture-atlas-20kg',
  'Peinture Atlas 20kg',
  200,
  25,
  'Peinture de finition resistante pour interieur et exterieur.',
  'Peinture Atlas de haute qualite avec excellente couvrance et bonne durabilite.',
  'peinture',
  4.8,
  array[
    '/images/products/peinture-atlas.jpg',
    '/images/products/peinture-atlas-detail-1.svg',
    '/images/products/peinture-atlas-detail-2.svg'
  ],
  true
),
(
  'ciment-50kg',
  'ciment-50kg',
  'Ciment 50kg',
  80,
  40,
  'Ciment solide pour construction et travaux.',
  'Ciment de qualite professionnelle adapte aux travaux de construction et de renovation.',
  'materiaux-construction',
  4.7,
  array['/images/products/ciment.jpg'],
  true
),
(
  'marteau-pro',
  'marteau-pro',
  'Marteau Pro',
  65,
  30,
  'Marteau robuste pour travaux de bricolage.',
  'Marteau solide et durable pour usage professionnel et domestique.',
  'outillage',
  4.5,
  array['/images/products/marteau-pro.jpg'],
  true
),
(
  'perceuse-bosch-750w',
  'perceuse-bosch-750w',
  'Perceuse Bosch 750W',
  350,
  12,
  'Perceuse puissante pour tous travaux.',
  'Perceuse performante ideale pour percage dans differents materiaux.',
  'outillage',
  4.6,
  array[
    '/images/products/perceuse-bosch.jpg',
    '/images/products/perceuse.jpg'
  ],
  true
),
(
  'tournevis-cruciforme',
  'tournevis-cruciforme',
  'Tournevis Cruciforme',
  30,
  55,
  'Tournevis pratique pour visser et devisser.',
  'Outil essentiel pour travaux de bricolage et maintenance.',
  'outillage',
  4.4,
  array['/images/products/tournevis.jpg'],
  true
),
(
  'cable-electrique-2-5mm-100m',
  'cable-electrique-2-5mm-100m',
  'Cable Electrique 2.5mm 100m',
  180,
  20,
  'Cable electrique securise et fiable.',
  'Cable de haute qualite pour installations electriques domestiques et professionnelles.',
  'electricite',
  4.5,
  array[
    '/images/products/cable-electrique-2-5mm-100m.jpg',
    '/images/products/cable.jpg'
  ],
  true
),
(
  'seau-peinture-10l',
  'seau-peinture-10l',
  'Seau Peinture 10L',
  55,
  40,
  'Seau pratique pour melange et application peinture.',
  'Seau solide 10 litres ideal pour peinture et petits travaux chantier.',
  'peinture',
  4.3,
  array['/images/products/peinture-atlas.svg'],
  true
),
(
  'pince-universelle',
  'pince-universelle',
  'Pince Universelle',
  48,
  38,
  'Pince polyvalente pour serrer et couper.',
  'Pince universelle en acier trempe pour usage quotidien.',
  'outillage',
  4.4,
  array['/images/products/marteau.jpg'],
  true
),
(
  'cle-a-molette-12',
  'cle-a-molette-12',
  'Cle a Molette 12',
  72,
  26,
  'Cle reglable pour ecrous et raccords.',
  'Cle a molette 12 pouces robuste pour plomberie et maintenance.',
  'outillage',
  4.5,
  array['/images/products/marteau-pro.jpg'],
  true
),
(
  'scie-a-main',
  'scie-a-main',
  'Scie a Main',
  85,
  22,
  'Scie manuelle pour bois et bricolage.',
  'Scie a main avec denture precise pour coupe propre.',
  'outillage',
  4.2,
  array['/images/products/marteau.jpg'],
  true
),
(
  'vis-placo-100pcs',
  'vis-placo-100pcs',
  'Vis Placo 100pcs',
  35,
  90,
  'Boite de vis pour plaque de platre.',
  'Vis placo phosphatee, fixation rapide et fiable.',
  'materiaux-construction',
  4.3,
  array['/images/products/ciment.jpg'],
  true
),
(
  'cheville-nylon-8mm-100pcs',
  'cheville-nylon-8mm-100pcs',
  'Cheville Nylon 8mm 100pcs',
  28,
  95,
  'Chevilles nylon pour fixation murale.',
  'Chevilles 8mm resistantes adaptees a plusieurs supports.',
  'materiaux-construction',
  4.2,
  array['/images/products/ciment.jpg'],
  true
),
(
  'silicone-neutre-300ml',
  'silicone-neutre-300ml',
  'Silicone Neutre 300ml',
  42,
  48,
  'Mastic silicone pour joints et etancheite.',
  'Silicone neutre haute adherence pour cuisine, salle de bain et facade.',
  'quincaillerie',
  4.4,
  array['/images/products/cable.jpg'],
  true
),
(
  'colle-carrelage-25kg',
  'colle-carrelage-25kg',
  'Colle Carrelage 25kg',
  95,
  34,
  'Colle performante pour pose carrelage.',
  'Mortier colle 25kg pour interieur et exterieur, forte adhesion.',
  'materiaux-construction',
  4.6,
  array['/images/products/ciment.jpg'],
  true
),
(
  'joint-carrelage-5kg',
  'joint-carrelage-5kg',
  'Joint Carrelage 5kg',
  40,
  37,
  'Joint de finition pour carrelage.',
  'Joint carrelage hydrofuge 5kg, finition propre et durable.',
  'materiaux-construction',
  4.3,
  array['/images/products/ciment.jpg'],
  true
),
(
  'rouleau-peinture-18cm',
  'rouleau-peinture-18cm',
  'Rouleau Peinture 18cm',
  24,
  60,
  'Rouleau pour application uniforme de peinture.',
  'Rouleau 18cm anti-traces pour murs et plafonds.',
  'peinture',
  4.4,
  array['/images/products/peinture-atlas-detail-1.svg'],
  true
),
(
  'brosse-peinture-100mm',
  'brosse-peinture-100mm',
  'Brosse Peinture 100mm',
  20,
  70,
  'Brosse large pour couches de finition.',
  'Brosse 100mm a poils resistants pour peinture acrylique et glycero.',
  'peinture',
  4.2,
  array['/images/products/peinture-atlas-detail-2.svg'],
  true
),
(
  'gants-protection-xl',
  'gants-protection-xl',
  'Gants Protection XL',
  18,
  80,
  'Gants de protection pour chantier.',
  'Gants resistants anti-abrasion pour manutention et bricolage.',
  'securite',
  4.1,
  array['/images/products/marteau.jpg'],
  true
),
(
  'masque-poussiere-ffp2',
  'masque-poussiere-ffp2',
  'Masque Poussiere FFP2',
  15,
  120,
  'Masque de protection contre poussiere fine.',
  'Masque FFP2 confortable pour travaux de poncage et demolition legere.',
  'securite',
  4.2,
  array['/images/products/ciment.jpg'],
  true
),
(
  'escabeau-3-marches',
  'escabeau-3-marches',
  'Escabeau 3 Marches',
  210,
  14,
  'Escabeau stable pour travaux en hauteur.',
  'Escabeau acier 3 marches avec patins anti-derapants.',
  'outillage',
  4.6,
  array['/images/products/perceuse.jpg'],
  true
),
(
  'rallonge-5m',
  'rallonge-5m',
  'Rallonge Electrique 5m',
  65,
  32,
  'Rallonge fiable pour alimentation outils.',
  'Rallonge 5 metres avec isolation renforcee pour chantier.',
  'electricite',
  4.5,
  array['/images/products/cable-electrique-2-5mm-100m.jpg'],
  true
),
(
  'interrupteur-simple',
  'interrupteur-simple',
  'Interrupteur Simple',
  22,
  110,
  'Interrupteur mural standard.',
  'Interrupteur simple design propre pour installation electrique domestique.',
  'electricite',
  4.2,
  array['/images/products/cable.jpg'],
  true
),
(
  'prise-double',
  'prise-double',
  'Prise Double',
  29,
  95,
  'Prise murale double securisee.',
  'Prise double 16A de qualite pour logement et bureau.',
  'electricite',
  4.3,
  array['/images/products/cable.jpg'],
  true
),
(
  'disjoncteur-16a',
  'disjoncteur-16a',
  'Disjoncteur 16A',
  58,
  50,
  'Disjoncteur de protection circuit.',
  'Disjoncteur 16A fiable contre surcharge et court-circuit.',
  'electricite',
  4.5,
  array['/images/products/cable-electrique-2-5mm-100m.jpg'],
  true
),
(
  'tube-pvc-32mm',
  'tube-pvc-32mm',
  'Tube PVC 32mm',
  36,
  75,
  'Tube PVC pour evacuation et plomberie.',
  'Tube PVC 32mm resistant a l''humidite et facile a poser.',
  'plomberie',
  4.3,
  array['/images/products/cable.jpg'],
  true
),
(
  'robinet-lavabo',
  'robinet-lavabo',
  'Robinet Lavabo',
  140,
  18,
  'Robinet chrome pour lavabo.',
  'Robinet lavabo finition chrome avec cartouche ceramique.',
  'plomberie',
  4.4,
  array['/images/products/cable.jpg'],
  true
),
(
  'javel-5l',
  'javel-5l',
  'Javel 5L',
  32,
  85,
  'Produit nettoyant et desinfectant.',
  'Javel 5 litres pour nettoyage profond des surfaces.',
  'droguerie',
  4.3,
  array['/images/products/tide.jpg'],
  true
),
(
  'lessive-tide-3kg',
  'lessive-tide-3kg',
  'Lessive Tide 3kg',
  95,
  46,
  'Lessive poudre haute performance.',
  'Lessive Tide 3kg pour linge propre et parfum durable.',
  'droguerie',
  4.6,
  array['/images/products/tide.jpg'],
  true
),
(
  'betonniere-mini',
  'betonniere-mini',
  'Betonniere Mini',
  2400,
  5,
  'Betonniere compacte pour petit chantier.',
  'Betonniere mini robuste pour melange ciment et mortier.',
  'materiaux-construction',
  4.7,
  array['/images/products/ciment.jpg'],
  true
),
(
  'meuleuse-125mm',
  'meuleuse-125mm',
  'Meuleuse 125mm',
  420,
  11,
  'Meuleuse performante pour coupe et poncage.',
  'Meuleuse 125mm puissante, adaptee aux travaux metal et maconnerie.',
  'outillage',
  4.6,
  array['/images/products/perceuse-electrique.svg'],
  true
)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  price = excluded.price,
  stock = excluded.stock,
  short_description = excluded.short_description,
  description = excluded.description,
  category_slug = excluded.category_slug,
  rating = excluded.rating,
  images = excluded.images,
  is_active = excluded.is_active,
  updated_at = now();
