-- Add ad monetization entities:
-- - pricing plans (ad_plans)
-- - tracking events (ad_events)
-- - optional plan link on ads (ads.plan_id)

create extension if not exists "pgcrypto";

create table if not exists public.ad_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text null,
  position text not null,
  duration_days integer not null,
  price integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint ad_plans_position_check check (position in ('top', 'middle')),
  constraint ad_plans_duration_days_check check (duration_days > 0),
  constraint ad_plans_price_check check (price >= 0)
);

create index if not exists idx_ad_plans_position on public.ad_plans(position);
create index if not exists idx_ad_plans_is_active on public.ad_plans(is_active);
create index if not exists idx_ad_plans_created_at on public.ad_plans(created_at desc);

alter table public.ads
add column if not exists plan_id uuid references public.ad_plans(id) on delete set null;

create index if not exists idx_ads_plan_id on public.ads(plan_id);

create table if not exists public.ad_events (
  id bigint generated by default as identity primary key,
  ad_id uuid not null references public.ads(id) on delete cascade,
  event_type text not null,
  session_key text null,
  dedupe_key text null,
  created_at timestamptz not null default now(),
  constraint ad_events_event_type_check check (event_type in ('view', 'click'))
);

create index if not exists idx_ad_events_ad_id on public.ad_events(ad_id);
create index if not exists idx_ad_events_event_type on public.ad_events(event_type);
create index if not exists idx_ad_events_created_at on public.ad_events(created_at desc);
create unique index if not exists idx_ad_events_dedupe_key_unique
on public.ad_events(dedupe_key)
where dedupe_key is not null;

alter table public.ad_plans enable row level security;
alter table public.ad_events enable row level security;
